"""create charities model

Revision ID: 01ec762f1e98
Revises: 83f406db3f5c
Create Date: 2024-09-09 12:30:25.529584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ec762f1e98'
down_revision = '83f406db3f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('charity_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employmentCaseStudy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charity_id', sa.Integer(), nullable=True))
        batch_op.alter_column('employer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_employmentCaseStudy_charity_id_charities'), 'charities', ['charity_id'], ['id'])

    with op.batch_alter_table('employmentReference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charity_id', sa.Integer(), nullable=True))
        batch_op.alter_column('employer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_employmentReference_charity_id_charities'), 'charities', ['charity_id'], ['id'])

    with op.batch_alter_table('keyRoles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charity_id', sa.Integer(), nullable=True))
        batch_op.alter_column('employer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_keyRoles_charity_id_charities'), 'charities', ['charity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyRoles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_keyRoles_charity_id_charities'), type_='foreignkey')
        batch_op.alter_column('employer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('charity_id')

    with op.batch_alter_table('employmentReference', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_employmentReference_charity_id_charities'), type_='foreignkey')
        batch_op.alter_column('employer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('charity_id')

    with op.batch_alter_table('employmentCaseStudy', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_employmentCaseStudy_charity_id_charities'), type_='foreignkey')
        batch_op.alter_column('employer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('charity_id')

    op.drop_table('charities')
    # ### end Alembic commands ###
