"""creating new models to show employment history

Revision ID: 1a5f2994cf6d
Revises: 1290ba1ac57a
Create Date: 2024-09-01 18:38:07.912792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5f2994cf6d'
down_revision = '1290ba1ac57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employmentHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('role_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employmentCaseStudy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('case_study_info', sa.String(), nullable=False),
    sa.Column('case_study_img', sa.String(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employmentHistory.id'], name=op.f('fk_employmentCaseStudy_employer_id_employmentHistory')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyRoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employmentHistory.id'], name=op.f('fk_keyRoles_employer_id_employmentHistory')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyRoles')
    op.drop_table('employmentCaseStudy')
    op.drop_table('employmentHistory')
    # ### end Alembic commands ###
