"""create an educational model

Revision ID: 209e602a3bf3
Revises: 1a5f2994cf6d
Create Date: 2024-09-03 10:23:48.249125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209e602a3bf3'
down_revision = '1a5f2994cf6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    # ### end Alembic commands ###
