"""create capstone project models

Revision ID: 66dbdbd3c1b1
Revises: e29f9201eab0
Create Date: 2024-09-03 12:14:12.701550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66dbdbd3c1b1'
down_revision = 'e29f9201eab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capstoneProject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('git_hub_link', sa.String(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['education_id'], ['education.id'], name=op.f('fk_capstoneProject_education_id_education')),
    sa.ForeignKeyConstraint(['employer_id'], ['employmentHistory.id'], name=op.f('fk_capstoneProject_employer_id_employmentHistory')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capstoneProject')
    # ### end Alembic commands ###
