"""update charity model to include dates and roles

Revision ID: 69a485cb24ee
Revises: fd02a0452d2e
Create Date: 2024-09-25 15:28:34.155945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a485cb24ee'
down_revision = 'fd02a0452d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.Date(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.String(), server_default='Present', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
