"""update the capstone project model

Revision ID: 83f406db3f5c
Revises: 66dbdbd3c1b1
Create Date: 2024-09-03 12:37:12.066585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f406db3f5c'
down_revision = '66dbdbd3c1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capstoneAchievments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievment', sa.String(), nullable=False),
    sa.Column('capstone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capstone_id'], ['capstoneProject.id'], name=op.f('fk_capstoneAchievments_capstone_id_capstoneProject')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capstoneProject', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capstoneProject', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.drop_table('capstoneAchievments')
    # ### end Alembic commands ###
