"""update education model with an omage variable

Revision ID: 90db96afe0ff
Revises: 209e602a3bf3
Create Date: 2024-09-03 10:25:00.245131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90db96afe0ff'
down_revision = '209e602a3bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_image', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_column('school_image')

    # ### end Alembic commands ###
