"""update education to include schools location

Revision ID: 99e84f1be5e1
Revises: 90db96afe0ff
Create Date: 2024-09-03 10:31:24.227912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e84f1be5e1'
down_revision = '90db96afe0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
