"""update education with subject_studied variable

Revision ID: ae64042c830f
Revises: 99e84f1be5e1
Create Date: 2024-09-03 10:45:28.304817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae64042c830f'
down_revision = '99e84f1be5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_studied', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_column('subject_studied')

    # ### end Alembic commands ###
