"""updated CapstoneProjects

Revision ID: fd02a0452d2e
Revises: 6b6c50b82bce
Create Date: 2024-09-17 14:51:21.962778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd02a0452d2e'
down_revision = '6b6c50b82bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capstoneProject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capstoneProject', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
